#!/usr/bin/env bash

xdg-user-dirs-update

mkdir -p ~/.completions
mkdir -p ~/.config/systemd/user
mkdir -p ~/.local/{bin,dbin,opt}
mkdir -p ~/.local/share/applications
mkdir -p ~/.local/share/icons/hicolor/64x64/apps

echo "All done!"
