#!/usr/bin/env bash

# Volume Control (Raise / Lower)
XF86Audio{Raise,Lower}Volume
    pactl set-sink-volume @DEFAULT_SINK@ {+,-}5% && \
    pactl get-sink-volume @DEFAULT_SINK@ | \
    awk -F/ -v id=$((16#497ffd90)) \
    '/Volume/ \{ \
        gsub(/ /,"",$2); gsub(/ /,"",$4); \
        val = ($4 ? "L " $2 " | R " $4 : "Vol " $2); \
        system("notify-send -r " id " -i audio-volume-high \"PulseAudio\" \"" val "\"") \
    \}'


# Mute Toggle
XF86AudioMute
    pactl set-sink-mute @DEFAULT_SINK@ toggle && \
    pactl get-sink-mute @DEFAULT_SINK@ | \
    awk -v id=$((16#7dbbf1e5)) \
    '\{ s=($2=="yes"?"muted":"medium"); \
    system("notify-send -r " id " -i audio-volume-" s " \"Volume " toupper(substr(s,1,1)) substr(s,2) "\"") \}'

# Media Controls
XF86Audio{Play,Next,Prev}
    playerctl {play-pause,next,previous}

# Keyboard Layout Toggle (US <-> FR)
ctrl + shift + k
    setxkbmap -query | \
    awk -v id=$((16#30ee8f58)) \
    '/layout/ \{ \
        new = ($2=="us" ? "fr" : "us"); \
        system("setxkbmap " new); \
        system("notify-send -r " id " -i input-keyboard \"Keyboard Map\" \"" toupper(new) "\"") \
    \}'

# Screenshots
# Grouped variants: Full, Select (-s), Focused (-u), Clipboard (-os)
{_,ctrl +,alt +}Print
    scrot { ,-s ,-u } ~/Pictures/Print/%Y-%m-%d-%H%M%S.png \
    -e 'notify-send -i image-x-generic "Screenshot saved" "$f"'

# Clipboard screenshot (Selection)
shift + Print
    scrot -s - | xclip -sel clipboard -target image/png  && notify-send -i image-x-generic "Screenshot copied to clipboard"
