#!/usr/bin/env bash

# Volume up
XF86AudioRaiseVolume
    NOTIFY_ID=$((16#497ffd90)); \
    pactl set-sink-volume @DEFAULT_SINK@ +5% && \
    read LEFT RIGHT <<< $(pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\d+%' | head -n2 | tr '\n' ' ') && \
    notify-send -r $NOTIFY_ID -i audio-volume-high "PulseAudio" "L $LEFT | R $RIGHT"

# Volume down
XF86AudioLowerVolume
    NOTIFY_ID=$((16#497ffd90)); \
    pactl set-sink-volume @DEFAULT_SINK@ -5% && \
    read LEFT RIGHT <<< $(pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\d+%' | head -n2 | tr '\n' ' ') && \
    notify-send -r $NOTIFY_ID -i audio-volume-low "PulseAudio" "L $LEFT | R $RIGHT"

# Volume mute
XF86AudioMute
    NOTIFY_ID=$((16#7dbbf1e5)); \
    pactl set-sink-mute @DEFAULT_SINK@ toggle && \
    MUTE=$(pactl get-sink-mute @DEFAULT_SINK@ | grep -o 'yes' | head -n1) && \
    if [ "$MUTE" = "yes" ]; then \
        notify-send -r $NOTIFY_ID -i audio-volume-muted "Volume Muted"; \
    else \
        notify-send -r $NOTIFY_ID -i audio-volume-high "Volume Unmuted"; \
    fi

# Media PLay
XF86AudioPlay
    playerctl play-pause;

# Media Next
XF86AudioNext
    playerctl next;

# Media Prev
XF86AudioPrev
    playerctl previous;

# Screenshots
Print
    scrot ~/Pictures/Print/%Y-%m-%d-%H%M%S.png && \
    notify-send -i image-x-generic "Screenshot saved"

ctrl + Print
    scrot -s ~/Pictures/Print/%Y-%m-%d-%H%M%S.png && \
    notify-send -i image-x-generic "Screenshot saved"

alt + Print
    scrot -u ~/Pictures/Print/%Y-%m-%d-%H%M%S.png && \
    notify-send -i image-x-generic "Focused window screenshot saved"

shift + Print
    scrot -s /tmp/screenshot.png && \
    xclip -selection clipboard -t image/png -i /tmp/screenshot.png && \
    notify-send -i image-x-generic "Screenshot copied to clipboard"

