#!/usr/bin/env bash

y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  command yazi "$@" --cwd-file="$tmp"
  IFS= read -r -d '' cwd <"$tmp"
  [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
  rm -f -- "$tmp"
}

pass-totp() {
  sed -n '2p' |
    awk -F'[?&=]' '{for(i=1;i<=NF;i++)if($i=="secret"){print $(i+1);exit}}' |
    totp-gen --clip --pretty
}
