#!/usr/bin/env bash

lnabs() {
  ln -s "$(realpath "$1")" "$2"
}

nohistory() {
  set +o history
  HISTFILE=/dev/null
  echo "Everyone suddenly went quiet."
}

function y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  command yazi "$@" --cwd-file="$tmp"
  IFS= read -r -d '' cwd <"$tmp"
  [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
  rm -f -- "$tmp"
}
