#!/usr/bin/env bash

whatip() {
  echo "Public IP:"
  if ping -c 1 -W 1 1.1.1.1 &>/dev/null; then
    printf "  %s\n" \
      "$(curl -s --max-time 2 ifconfig.me || echo 'failed to fetch')"
  else
    echo "  (offline)"
  fi

  echo "Local IP(s):"
  ip -4 -o addr show scope global |
    awk '{printf "  %-8s %s\n", $2":", $4}' |
    cut -d/ -f1
}

gpg-here() {
  local dirpath="$PWD/.gnupg"
  export GNUPGHOME="$dirpath"
}

pass-here() {
  local dirpath="$PWD/password-store"
  export PASSWORD_STORE_DIR="$dirpath"
}

genpin() {
  local digits="${1:-6}"
  tr -dc '0-9' </dev/urandom | head -c "$digits"
  echo
}

y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  command yazi "$@" --cwd-file="$tmp"
  IFS= read -r -d '' cwd <"$tmp"
  [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
  rm -f -- "$tmp"
}
