#!/usr/bin/env bash

gpg-here() {
  local dirpath="$PWD/.gnupg"
  export GNUPGHOME="$dirpath"
}

pass-here() {
  local dirpath="$PWD/password-store"
  export PASSWORD_STORE_DIR="$dirpath"
}

genpin() {
  local digits="${1:-6}"
  tr -dc '0-9' </dev/urandom | head -c "$digits"
  echo
}

y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  command yazi "$@" --cwd-file="$tmp"
  IFS= read -r -d '' cwd <"$tmp"
  [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
  rm -f -- "$tmp"
}
